Repository godotengine/godot-vscode-plugin, pull requests merged in 2020-10, with the labels that each got.

#234 Document access to the class reference from the extension
  README.md
Labels: documentation, enhancement

#236 Check for updates to GitHub Actions every weekday
  .github/dependabot.yml
Labels: enhancement

#245 Clarify the function of the extra integer given by the debugger
  src/debugger/mediator.ts
Labels: bug

#247 Fixed the syntax of the escaped characters in strings
  syntaxes/GDScript.tmLanguage.json
Labels: bug

#246 Remove the configuration item 'godot-tools.check_config' as it has no effect
  package.json
Labels: bug
