Repository godotengine/godot-vscode-plugin, pull requests merged in 2022-03, with the labels that each got.

#330 Improve syntax highlighting
  syntaxes/GDScript.tmLanguage.json
Labels: bug, enhancement

#326 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#313 Update dependencies, recommend local TypeScript and vsce
  .github/workflows/ci.yml
  README.md
  package-lock.json
  package.json
Labels: enhancement

#316 Update extension metadata for better presentation on VS Marketplace
  LICENSE
  icon.png
  package.json
Labels: enhancement

#279 Fix "static func" indent error
  configurations/gdscript-configuration.json
Labels: bug

#297 Add support for setting language-server-host
  package.json
  src/godot-tools.ts
  src/lsp/GDScriptLanguageClient.ts
  src/lsp/MessageIO.ts
Labels: enhancement

#303 fixes #302 handling of Windows terminals determined by profiles
  src/godot-tools.ts
Labels: bug

#264 Update client to v7.0.0 to use 3.16.0 spec
  package-lock.json
  package.json
  src/godot-tools.ts
  src/lsp/GDScriptLanguageClient.ts
  src/lsp/MessageIO.ts
  src/lsp/NativeDocumentManager.ts
  src/lsp/gdscript.capabilities.ts
Labels: enhancement

#332 Add macOS editor location to README since it's not obvious
  README.md
Labels: enhancement
