Repository godotengine/godot-vscode-plugin, pull requests merged in 2022-08, with the labels that each got.

#397 Update gdshader syntax
  syntaxes/GDShader.tmLanguage.json
Labels: enhancement

#403 Add highlighting support for %Unique nodes in NodePaths
  syntaxes/GDScript.tmLanguage.json
  syntaxes/examples/gdscript1.gd
Labels: enhancement

#402 Fix OS singleton being incorrectly highlighted as a constant
  syntaxes/GDScript.tmLanguage.json
  syntaxes/examples/gdscript1.gd
Labels: bug

#404 Improve displaying symbols documentation
  package-lock.json
  package.json
  src/lsp/NativeDocumentManager.ts
Labels: enhancement

#408 Improve extension startup performance
  .vscodeignore
  package-lock.json
  package.json
  src/debugger/commands/command_parser.ts
  src/debugger/debugger_context.ts
  src/godot-tools.ts
  src/lsp/MessageIO.ts
Labels: enhancement

#363 Add "additional options" to launch debugger with
  package.json
  src/debugger/debug_session.ts
  src/debugger/debugger_context.ts
  src/debugger/mediator.ts
  src/debugger/server_controller.ts
Labels: enhancement

#411 Add `_physics_process` snippet
  configurations/snippets.json
Labels: enhancement

#407 Fix various highlighting errors
  syntaxes/GDScript.tmLanguage.json
  syntaxes/examples/gdscript1.gd
  syntaxes/examples/gdscript2.gd
Labels: bug, enhancement

#410 Fix internal document link handling
  src/document_link_provider.ts
  src/godot-tools.ts
  src/lsp/GDScriptLanguageClient.ts
  syntaxes/examples/Example.gd
  syntaxes/examples/Example.tscn
  syntaxes/examples/project.godot
  syntaxes/examples/rainbow_gradient_shader.tres
Labels: bug, enhancement

#405 Add "Open Type Documentation" context menu option
  package.json
  src/godot-tools.ts
  src/lsp/GDScriptLanguageClient.ts
  src/lsp/NativeDocumentManager.ts
Labels: enhancement
